# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f22a80eb8bd0bf32ef89f6b63b2083cd524adf985700e721bd7d97dcf03992a48cacdaa6c2624df1a46db866e65b0dc7dd8622bf98c6252218df23fb66ab92dc

test:
  secret_key_base: 00cc54f552253bcb4d81d97a041b46d1e4e54e72013795998eccb89cbc005189f5ee25fa215c91200f98797e423674135ccfa91ac4c31801d3f99397abd1b348

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
